import { beforeEach, expect, it, vi } from 'vitest';
const m=vi.hoisted(()=>({config:vi.fn(),send:vi.fn()}));
vi.mock('server-only',()=>({}));
vi.mock('@/lib/server/mailjet-connection',()=>({getMailjetConfig:m.config}));
vi.mock('@/lib/email/mailjet',()=>({sendMailjetMessage:m.send}));
import { sendTransactionalEmail } from './transactional-email';
const message={orgId:'org-a',to:'recipient@example.com',subject:'Test',html:'<p>Test</p>',idempotencyKey:'test-1'};
beforeEach(()=>vi.clearAllMocks());
it('does not send without an org connection',async()=>{m.config.mockResolvedValue(null);expect((await sendTransactionalEmail(message)).status).toBe('UNAVAILABLE');expect(m.send).not.toHaveBeenCalled();});
it('passes the organization-scoped credentials and preserves provider errors',async()=>{m.config.mockResolvedValue({apiKey:'key'});m.send.mockResolvedValue({status:'FAILED',providerMessageId:null,error:'Mailjet rejected message'});expect((await sendTransactionalEmail(message)).status).toBe('FAILED');expect(m.config).toHaveBeenCalledWith('org-a');expect(m.send).toHaveBeenCalledWith({apiKey:'key'},message);});
it('hides credential and persistence errors',async()=>{m.config.mockRejectedValue(new Error('private details'));const result=await sendTransactionalEmail(message);expect(result.status).toBe('UNAVAILABLE');expect(result.error).not.toContain('private details');});
