import { createHash } from 'node:crypto';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { basename, resolve } from 'node:path';

const root = process.cwd();
const slug = basename(root)
  .toLowerCase()
  .replace(/[^a-z0-9]+/g, '_')
  .replace(/^_+|_+$/g, '');
const digest = createHash('sha1').update(root).digest('hex');
const port = 3100 + (Number.parseInt(digest.slice(0, 4), 16) % 800);
const dbName = `picc_crm_${slug || digest.slice(0, 8)}`.slice(0, 60);
const envPath = resolve(root, '.env.local');
const examplePath = resolve(root, '.env.local.example');

const base = existsSync(envPath)
  ? readFileSync(envPath, 'utf8')
  : existsSync(examplePath)
    ? readFileSync(examplePath, 'utf8')
    : '';

const nextValues = new Map(
  base
    .split(/\r?\n/)
    .filter((line) => line.trim() && !line.trim().startsWith('#') && line.includes('='))
    .map((line) => {
      const index = line.indexOf('=');
      return [line.slice(0, index), line.slice(index + 1)];
    }),
);

nextValues.set('DEMO_MODE', 'true');
nextValues.set('DEMO_ORG_ID', nextValues.get('DEMO_ORG_ID') || 'org_picc_demo');
nextValues.set('DEMO_USER_ID', nextValues.get('DEMO_USER_ID') || 'demo_user');
nextValues.set('TERRITORY_ORG_ID', nextValues.get('TERRITORY_ORG_ID') || 'org_picc_demo');
nextValues.set('PICC_AGENT_DEV_PORT', String(port));
nextValues.set('PICC_AGENT_DB_NAME', dbName);
nextValues.set('DATABASE_URL', `postgresql://postgres:postgres@localhost:5432/${dbName}?schema=public`);

const rendered = [
  '# Generated by npm run worktree:setup. Safe to edit locally; do not commit.',
  ...Array.from(nextValues.entries()).map(([key, value]) => `${key}=${value}`),
  '',
].join('\n');

writeFileSync(envPath, rendered);

console.log(`Wrote ${envPath}`);
console.log(`PICC_AGENT_DEV_PORT=${port}`);
console.log(`PICC_AGENT_DB_NAME=${dbName}`);
